<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ASCDK041" name="Test" tests="4" failures="1" timestamp="18 May 2016 07:10:15 GMT" time="138.652" errors="0">
  <testcase name="phoneNumberText" time="65.424" classname="com.pack.test.EnterPhoneNumberTest"/>
  <testcase name="cancelRechargeTest" time="13.836" classname="com.pack.test.EnterPhoneNumberTest"/>
  <testcase name="failedTest" time="0.875" classname="com.pack.test.EnterPhoneNumberTest">
    <failure type="java.lang.AssertionError" message="expected [Payment Confirmation Awaited1] but found [Payment Confirmation Awaited]">
      <![CDATA[java.lang.AssertionError: expected [Payment Confirmation Awaited1] but found [Payment Confirmation Awaited]
	at com.pack.page.Recharge.getFailedMessage1(Recharge.java:265)
	at com.pack.test.EnterPhoneNumberTest.failedTest(EnterPhoneNumberTest.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- failedTest -->
  <testcase name="testCaseSkip" time="0.0" classname="com.pack.test.EnterPhoneNumberTest">
    <skipped/>
  </testcase> <!-- testCaseSkip -->
</testsuite> <!-- Test -->
